CREATE DATABASE Mercearia
GO

CREATE TABLE Produtos(
Id_Produto INT PRIMARY KEY IDENTITY(1,1)NOT NULL, 
Nome VARCHAR(80) NOT NULL,
Cod_Barra INT,
Preco INT NOT NULL
);
GO

CREATE TABLE Vendedor(
Id_Vendedor INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Nome_Vendedor VARCHAR(80) NOT NULL,
Senha INT NOT NULL
);
GO

CREATE TABLE Vendas(
Id_Venda INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Nome_Produto VARCHAR(50) NOT NULL,
Preco INT  NOT NULL,
Id_Vendedor INT FOREIGN KEY REFERENCES Vendedor(Id_Vendedor) NOT NULL
);
GO
CREATE TABLE Pessoa(
Id_Pessoa INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Nome_Pessoa VARCHAR
);
GO

CREATE TABLE Contas(
Id_Venda INT FOREIGN KEY REFERENCES Vendas(Id_Venda) NOT NULL,
Id_Pessoa INT FOREIGN KEY REFERENCES Pessoa(Id_Pessoa) NULL,
Produto VARCHAR(50) NOT NULL,
Preco INT NOT NULL
);
GO
