//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contas
    {
        public int Id_Venda { get; set; }
        public Nullable<int> Id_Pessoa { get; set; }
        public string Produto { get; set; }
        public int Preco { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Vendas Vendas { get; set; }
    }
}
